In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nfl-big-data-bowl-2025/players.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_7.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_9.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_6.csv
/kaggle/input/nfl-big-data-bowl-2025/games.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_8.csv
/kaggle/input/nfl-big-data-bowl-2025/player_play.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_4.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_3.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_5.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_1.csv
/kaggle/input/nfl-big-data-bowl-2025/plays.csv
/kaggle/input/nfl-big-data-bowl-2025/tracking_week_2.csv

In [9]:
import pandas as pd

# Load the data

tracking = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/tracking_week_1.csv')
plays = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/plays.csv')

# Preview the structure
print(tracking.columns)
print(plays.columns)

Index(['gameId', 'playId', 'nflId', 'displayName', 'frameId', 'frameType',
       'time', 'jerseyNumber', 'club', 'playDirection', 'x', 'y', 's', 'a',
       'dis', 'o', 'dir', 'event'],
      dtype='object')
Index(['gameId', 'playId', 'playDescription', 'quarter', 'down', 'yardsToGo',
       'possessionTeam', 'defensiveTeam', 'yardlineSide', 'yardlineNumber',
       'gameClock', 'preSnapHomeScore', 'preSnapVisitorScore',
       'playNullifiedByPenalty', 'absoluteYardlineNumber',
       'preSnapHomeTeamWinProbability', 'preSnapVisitorTeamWinProbability',
       'expectedPoints', 'offenseFormation', 'receiverAlignment',
       'playClockAtSnap', 'passResult', 'passLength', 'targetX', 'targetY',
       'playAction', 'dropbackType', 'dropbackDistance', 'passLocationType',
       'timeToThrow', 'timeInTackleBox', 'timeToSack', 'passTippedAtLine',
       'unblockedPressure', 'qbSpike', 'qbKneel', 'qbSneak',
       'rushLocationType', 'penaltyYards', 'prePenaltyYardsGained',
       'yardsGained', 'homeTeamWinProbabilityAdded',
       'visitorTeamWinProbilityAdded', 'expectedPointsAdded', 'isDropback',
       'pff_runConceptPrimary', 'pff_runConceptSecondary', 'pff_runPassOption',
       'pff_passCoverage', 'pff_manZone'],
      dtype='object')

In [49]:
display(plays.head(20))
# print(plays.playDescription)
all_descriptions = " ".join(plays['playDescription'].dropna().astype(str))
print(all_descriptions[:500])

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,yardsGained,homeTeamWinProbabilityAdded,visitorTeamWinProbilityAdded,expectedPointsAdded,isDropback,pff_runConceptPrimary,pff_runConceptSecondary,pff_runPassOption,pff_passCoverage,pff_manZone
0,2022102302,2655,(1:54) (Shotgun) J.Burrow pass short middle to...,3,1,10,CIN,ATL,CIN,21,...,9,0.004634,-0.004634,0.702717,True,NaN,NaN,0,Cover-3,Zone
1,2022091809,3698,(2:13) (Shotgun) J.Burrow pass short right to ...,4,1,10,CIN,DAL,CIN,8,...,4,0.002847,-0.002847,-0.240509,True,NaN,NaN,0,Quarters,Zone
2,2022103004,3146,(2:00) (Shotgun) D.Mills pass short right to D...,4,3,12,HOU,TEN,HOU,20,...,6,0.000205,-0.000205,-0.218480,True,NaN,NaN,0,Quarters,Zone
3,2022110610,348,(9:28) (Shotgun) P.Mahomes pass short left to ...,1,2,10,KC,TEN,TEN,23,...,4,-0.001308,0.001308,-0.427749,True,NaN,NaN,0,Quarters,Zone
4,2022102700,2799,(2:16) (Shotgun) L.Jackson up the middle to TB...,3,2,8,BAL,TB,TB,27,...,-1,0.027141,-0.027141,-0.638912,False,MAN,READ OPTION,0,Cover-1,Man
5,2022100205,2314,(14:15) Ja.Williams up the middle to DET 32 fo...,3,2,6,DET,SEA,DET,29,...,3,-0.024210,0.024210,-0.442517,False,MAN,NaN,0,Cover 6-Left,Zone
6,2022110605,3861,(:29) (Shotgun) J.Wilkins up the middle to IND...,4,1,10,IND,NE,IND,40,...,5,0.002189,-0.002189,-0.991169,False,INSIDE ZONE,NaN,0,Cover-2,Zone
7,2022100203,3994,(:35) K.Murray kneels to CAR 29 for -1 yards.,4,3,12,ARI,CAR,CAR,28,...,-1,-0.005253,0.005253,0.000000,False,UNDEFINED,NaN,0,NaN,NaN
8,2022091104,3662,(12:51) (Shotgun) J.Hurts pass incomplete shor...,4,3,12,PHI,DET,PHI,35,...,0,0.012361,-0.012361,-1.161621,True,NaN,NaN,0,Cover-0,Man
9,2022100204,1422,(5:22) (Shotgun) C.Rush pass short left to M.G...,2,3,8,DAL,WAS,DAL,35,...,15,0.058490,-0.058490,2.194760,True,NaN,NaN,0,Quarters,Zone
10,2022100912,445,(8:51) (Shotgun) C.Rush pass incomplete short ...,1,3,5,DAL,LA,LA,15,...,0,0.034006,-0.034006,-1.288449,True,NaN,NaN,0,Cover-3 Seam,Zone
11,2022102306,3240,(12:55) (Shotgun) A.Dillon left tackle to WAS ...,4,2,10,GB,WAS,WAS,46,...,0,0.053308,-0.053308,-0.962012,False,PULL LEAD,NaN,0,Cover-6 Right,Zone
12,2022091112,1674,(:35) (Shotgun) A.Rodgers pass deep left inten...,2,1,10,GB,MIN,GB,25,...,0,0.003262,-0.003262,-1.071627,True,NaN,NaN,0,Cover-2,Zone
13,2022110603,2325,"(7:36) (No Huddle, Shotgun) A.Rodgers pass sho...",3,2,9,GB,DET,GB,47,...,12,-0.044392,0.044392,1.286698,True,NaN,NaN,0,Quarters,Zone
14,2022092511,1310,(9:41) (Shotgun) M.Mariota scrambles left end ...,2,2,7,ATL,SEA,SEA,38,...,2,0.000543,-0.000543,-0.266228,True,OUTSIDE ZONE,NaN,0,Cover-3 Seam,Zone
15,2022100212,2463,(3:18) J.Herron reported in as eligible. J.Ja...,3,1,1,LV,DEN,DEN,1,...,-2,-0.017039,0.017039,-0.822176,False,MAN,LEAD,0,Goal Line,Other
16,2022100913,2604,(6:08) (Shotgun) J.Burrow pass short right to ...,3,3,6,CIN,BAL,BAL,20,...,7,-0.041198,0.041198,1.304587,True,NaN,NaN,0,Cover 6-Left,Zone
17,2022102308,3304,"(2:57) (No Huddle, Shotgun) D.Mills pass incom...",4,2,1,HOU,LV,HOU,29,...,0,0.000007,-0.000007,-0.373242,True,NaN,NaN,0,Quarters,Zone
18,2022110607,3178,(9:59) (Shotgun) T.Heinicke pass short left to...,4,2,7,WAS,MIN,WAS,28,...,-2,-0.016307,0.016307,-0.708830,True,NaN,NaN,0,Quarters,Zone
19,2022100207,681,(4:32) R.Tannehill pass deep left to C.Okonkwo...,1,1,10,TEN,IND,IND,42,...,23,-0.051718,0.051718,1.438245,True,OUTSIDE ZONE,NaN,0,Cover-3,Zone

(1:54) (Shotgun) J.Burrow pass short middle to T.Boyd to CIN 30 for 9 yards (J.Hawkins). (2:13) (Shotgun) J.Burrow pass short right to H.Hurst to CIN 12 for 4 yards (L.Vander Esch). (2:00) (Shotgun) D.Mills pass short right to D.Pierce to HST 26 for 6 yards (D.Walker). (9:28) (Shotgun) P.Mahomes pass short left to I.Pacheco to TEN 19 for 4 yards (Z.Cunningham). (2:16) (Shotgun) L.Jackson up the middle to TB 28 for -1 yards (R.Nunez-Roches). (14:15) Ja.Williams up the middle to DET 32 for 3 yards

In [51]:
players = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/players.csv')
print(players.columns)

Index(['nflId', 'height', 'weight', 'birthDate', 'collegeName', 'position',
       'displayName'],
      dtype='object')

In [55]:
import pandas as pd

# Load player data
players = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/players.csv')

# Simple case-insensitive substring match for "Boyd"
boyd_matches = players[players['displayName'].str.contains("boyd", case=False, na=False)]

print("📌 Players matching 'Boyd':")
display(boyd_matches)

📌 Players matching 'Boyd':

     nflId height  weight   birthDate collegeName position displayName
322  43344    6-2     203  1994-11-15  Pittsburgh       WR  Tyler Boyd
909  48000   5-11     201  1996-09-12       Texas       CB   Kris Boyd

In [36]:
players = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/players.csv')
print(players.columns)
display(players.head(15))

Index(['nflId', 'height', 'weight', 'birthDate', 'collegeName', 'position',
       'displayName'],
      dtype='object')

,nflId,height,weight,birthDate,collegeName,position,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
2,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
3,30842,6-6,267,1984-05-19,UCLA,TE,Marcedes Lewis
4,33084,6-4,217,1985-05-17,Boston College,QB,Matt Ryan
5,33099,6-6,245,1985-01-16,Delaware,QB,Joe Flacco
6,33107,6-4,315,1985-08-30,Virginia Tech,T,Duane Brown
7,33130,5-10,175,1986-12-01,California,WR,DeSean Jackson
8,33131,6-8,300,1986-09-01,Miami,DE,Calais Campbell
9,33138,6-3,222,1985-07-02,Michigan,QB,Chad Henne
10,33234,6-0,205,1985-09-09,UCLA,WR,Matt Slater
11,34452,6-3,220,1988-02-07,Georgia,QB,Matthew Stafford
12,34754,6-0,229,1986-10-07,Missouri,QB,Chase Daniel
13,34843,6-2,215,1985-10-13,Michigan State,QB,Brian Hoyer
14,35443,6-5,320,1988-07-19,Oklahoma,T,Trent Williams

In [43]:
import pandas as pd

# Define play ID
game_id = 2022091200
play_id = 3980

# Load data
# tracking = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/tracking_week1.csv')
players = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/players.csv')
tracking_filtered = tracking[(tracking['gameId'] == game_id) & (tracking['playId'] == play_id)]
tracking_with_position = tracking_filtered.merge(players[['nflId', 'position']], on='nflId', how='left')
qb_data = tracking_with_position[tracking_with_position['position'] == 'QB']
qb_names = qb_data['displayName'].unique()

positions_in_play = tracking_with_position['position'].dropna().unique()

print(f"📌 Player positions in gameId = {game_id}, playId = {play_id}:")
print(sorted(positions_in_play))
qb_name = qb_names[0]
qb_tracking = tracking_filtered[tracking_filtered['displayName'] == qb_name]

# Output
print(f"🏈 Quarterback identified: {qb_name}")
print(f"\nTracking data for QB '{qb_name}' in gameId = {game_id}, playId = {play_id}:")
display(qb_tracking.head(10))
print(f"Total QB frames: {qb_tracking.shape[1]}")

📌 Player positions in gameId = 2022091200, playId = 3980:
['C', 'CB', 'DE', 'FS', 'G', 'ILB', 'NT', 'OLB', 'QB', 'RB', 'SS', 'T', 'TE', 'WR']
🏈 Quarterback identified: Geno Smith

Tracking data for QB 'Geno Smith' in gameId = 2022091200, playId = 3980:

,gameId,playId,nflId,displayName,frameId,frameType,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
433174,2022091200,3980,39987.0,Geno Smith,1,BEFORE_SNAP,2022-09-13 03:11:50.3,7.0,SEA,right,57.80,22.84,0.18,0.18,0.02,37.69,317.39,NaN
433175,2022091200,3980,39987.0,Geno Smith,2,BEFORE_SNAP,2022-09-13 03:11:50.4,7.0,SEA,right,57.79,22.86,0.22,0.22,0.02,41.71,324.54,NaN
433176,2022091200,3980,39987.0,Geno Smith,3,BEFORE_SNAP,2022-09-13 03:11:50.5,7.0,SEA,right,57.78,22.88,0.27,0.35,0.03,43.61,336.72,NaN
433177,2022091200,3980,39987.0,Geno Smith,4,BEFORE_SNAP,2022-09-13 03:11:50.6,7.0,SEA,right,57.77,22.91,0.32,0.44,0.03,44.73,343.34,NaN
433178,2022091200,3980,39987.0,Geno Smith,5,BEFORE_SNAP,2022-09-13 03:11:50.7,7.0,SEA,right,57.76,22.94,0.34,0.42,0.03,47.29,352.97,NaN
433179,2022091200,3980,39987.0,Geno Smith,6,BEFORE_SNAP,2022-09-13 03:11:50.8,7.0,SEA,right,57.77,22.98,0.40,0.56,0.04,45.55,7.02,NaN
433180,2022091200,3980,39987.0,Geno Smith,7,BEFORE_SNAP,2022-09-13 03:11:50.9,7.0,SEA,right,57.77,23.02,0.44,0.53,0.04,46.64,11.66,NaN
433181,2022091200,3980,39987.0,Geno Smith,8,BEFORE_SNAP,2022-09-13 03:11:51,7.0,SEA,right,57.79,23.07,0.54,0.61,0.05,43.78,17.62,NaN
433182,2022091200,3980,39987.0,Geno Smith,9,BEFORE_SNAP,2022-09-13 03:11:51.1,7.0,SEA,right,57.82,23.12,0.61,0.74,0.06,44.76,27.37,NaN
433183,2022091200,3980,39987.0,Geno Smith,10,BEFORE_SNAP,2022-09-13 03:11:51.2,7.0,SEA,right,57.86,23.18,0.72,0.85,0.07,51.87,36.18,NaN

Total QB frames: 18

In [45]:
wr_data = tracking_with_position[tracking_with_position['position'] == 'WR']
wr_names = wr_data['displayName'].unique()

wr_name = wr_names[0]
wr_tracking = tracking_filtered[tracking_filtered['displayName'] == wr_name]

# Output
print(f"Wide Receiver identified: {wr_name}")
print(f"\nTracking data for WR '{wr_name}' in gameId = {game_id}, playId = {play_id}:")
display(wr_tracking.head(10))
print(f"Total QB frames: {wr_tracking.shape[1]}")

Wide Receiver identified: Marquise Goodwin

Tracking data for WR 'Marquise Goodwin' in gameId = 2022091200, playId = 3980:

,gameId,playId,nflId,displayName,frameId,frameType,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
433235,2022091200,3980,40026.0,Marquise Goodwin,1,BEFORE_SNAP,2022-09-13 03:11:50.3,11.0,SEA,right,56.94,23.49,0.78,1.43,0.07,53.83,282.86,NaN
433236,2022091200,3980,40026.0,Marquise Goodwin,2,BEFORE_SNAP,2022-09-13 03:11:50.4,11.0,SEA,right,56.85,23.51,1.03,1.67,0.10,69.60,283.30,NaN
433237,2022091200,3980,40026.0,Marquise Goodwin,3,BEFORE_SNAP,2022-09-13 03:11:50.5,11.0,SEA,right,56.74,23.53,1.21,1.58,0.11,68.63,283.10,NaN
433238,2022091200,3980,40026.0,Marquise Goodwin,4,BEFORE_SNAP,2022-09-13 03:11:50.6,11.0,SEA,right,56.61,23.56,1.38,1.40,0.13,73.52,283.13,NaN
433239,2022091200,3980,40026.0,Marquise Goodwin,5,BEFORE_SNAP,2022-09-13 03:11:50.7,11.0,SEA,right,56.47,23.59,1.53,1.18,0.15,74.27,281.47,NaN
433240,2022091200,3980,40026.0,Marquise Goodwin,6,BEFORE_SNAP,2022-09-13 03:11:50.8,11.0,SEA,right,56.31,23.62,1.66,1.01,0.16,74.27,279.74,NaN
433241,2022091200,3980,40026.0,Marquise Goodwin,7,BEFORE_SNAP,2022-09-13 03:11:50.9,11.0,SEA,right,56.14,23.64,1.74,0.80,0.17,76.03,277.89,NaN
433242,2022091200,3980,40026.0,Marquise Goodwin,8,BEFORE_SNAP,2022-09-13 03:11:51,11.0,SEA,right,55.96,23.66,1.81,0.62,0.18,76.88,276.18,NaN
433243,2022091200,3980,40026.0,Marquise Goodwin,9,BEFORE_SNAP,2022-09-13 03:11:51.1,11.0,SEA,right,55.78,23.68,1.84,0.54,0.18,79.28,273.99,NaN
433244,2022091200,3980,40026.0,Marquise Goodwin,10,BEFORE_SNAP,2022-09-13 03:11:51.2,11.0,SEA,right,55.60,23.69,1.87,0.48,0.19,82.11,272.57,NaN

Total QB frames: 18

In [21]:
import pandas as pd

game_id = 2022091200

# 1. Get all plays from that game
plays_filtered = plays[plays['gameId'] == game_id]

print("🔍 Plays for gameId = 2022091200:")
display(plays_filtered.head(10))
# # 2. Get all tracking data for that game
# tracking_filtered = tracking[tracking['gameId'] == game_id]

# print(f"\n🎯 Tracking data for gameId = {game_id}:")
# print(tracking_filtered.head())

🔍 Plays for gameId = 2022091200:

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,yardsGained,homeTeamWinProbabilityAdded,visitorTeamWinProbilityAdded,expectedPointsAdded,isDropback,pff_runConceptPrimary,pff_runConceptSecondary,pff_runPassOption,pff_passCoverage,pff_manZone
286,2022091200,3980,(:09) G.Smith kneels to DEN 49 for -1 yards.,4,3,12,SEA,DEN,DEN,48,...,-1,0.011515,-0.011515,0.000000,False,UNDEFINED,NaN,0,NaN,NaN
566,2022091200,3574,(3:25) (Shotgun) R.Wilson pass incomplete shor...,4,2,5,DEN,SEA,DEN,27,...,0,0.063136,-0.063136,-0.575654,True,NaN,NaN,0,Cover 6-Left,Zone
593,2022091200,1465,(4:20) G.Smith pass incomplete short left to R...,2,1,10,SEA,DEN,SEA,37,...,0,-0.014644,0.014644,-0.535125,True,OUTSIDE ZONE,NaN,0,Cover-3 Seam,Zone
723,2022091200,109,(13:38) (Shotgun) G.Smith pass short middle to...,1,3,3,SEA,DEN,SEA,37,...,17,0.044197,-0.044197,2.206573,True,NaN,NaN,0,Cover-3 Seam,Zone
821,2022091200,286,(11:18) R.Wilson pass short right to A.Beck to...,1,2,10,DEN,SEA,DEN,11,...,25,-0.053480,0.053480,2.353510,True,OUTSIDE ZONE,NaN,0,Cover-6 Right,Zone
830,2022091200,1299,(7:20) J.Williams right guard to DEN 24 for -1...,2,1,10,DEN,SEA,DEN,25,...,-1,0.017426,-0.017426,-1.156474,False,INSIDE ZONE,PITCH;SPLIT,0,Quarters,Zone
1301,2022091200,3515,(4:54) (Shotgun) G.Smith sacked at SEA 24 for ...,4,3,6,SEA,DEN,SEA,34,...,-10,-0.170094,0.170094,-1.966423,True,NaN,NaN,0,Cover-1,Man
1366,2022091200,1988,(14:20) M.Gordon up the middle to DEN 26 for 8...,3,2,12,DEN,SEA,DEN,18,...,8,-0.014610,0.014610,0.290619,False,POWER,LEAD,0,Cover 6-Left,Zone
1414,2022091200,180,(12:19) R.Penny left guard to DEN 38 for 4 yar...,1,2,6,SEA,DEN,DEN,42,...,4,-0.012123,0.012123,-0.162190,False,INSIDE ZONE,NaN,0,Cover-3,Zone
1440,2022091200,2093,(11:35) (Shotgun) R.Wilson pass short left to ...,3,1,10,DEN,SEA,SEA,36,...,1,0.023995,-0.023995,-0.397402,True,NaN,NaN,0,Cover 6-Left,Zone

In [29]:
import pandas as pd

game_id = 2022091200
play_id = 3980

# 2. Get all tracking data for that game
tracking_filtered = tracking[(tracking['gameId'] == game_id) & (tracking['playId'] == play_id)]
#tracking_filtered = tracking[(tracking['gameId'] == game_id)]

print(f"Tracking data for gameId = {game_id}:")
display(tracking_filtered.head(10))
print(f"\nRow count of tracking data for gameId = {game_id}:")
print(tracking.shape[0])

player_row_counts = tracking_filtered.groupby('displayName').size().reset_index(name='row_count')
player_row_counts = player_row_counts.sort_values(by='row_count', ascending=False)
player_row_counts['row_number'] = player_row_counts.index + 1
player_row_counts = player_row_counts.sort_values(by='row_number').reset_index(drop=True)
display(player_row_counts)

Tracking data for gameId = 2022091200:

,gameId,playId,nflId,displayName,frameId,frameType,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
433113,2022091200,3980,35459.0,Kareem Jackson,1,BEFORE_SNAP,2022-09-13 03:11:50.3,22.0,DEN,right,73.12,25.70,0.43,0.32,0.04,249.79,298.73,NaN
433114,2022091200,3980,35459.0,Kareem Jackson,2,BEFORE_SNAP,2022-09-13 03:11:50.4,22.0,DEN,right,73.09,25.73,0.44,0.25,0.04,247.62,301.34,NaN
433115,2022091200,3980,35459.0,Kareem Jackson,3,BEFORE_SNAP,2022-09-13 03:11:50.5,22.0,DEN,right,73.05,25.75,0.43,0.20,0.04,245.20,304.24,NaN
433116,2022091200,3980,35459.0,Kareem Jackson,4,BEFORE_SNAP,2022-09-13 03:11:50.6,22.0,DEN,right,73.02,25.77,0.39,0.20,0.04,243.02,305.67,NaN
433117,2022091200,3980,35459.0,Kareem Jackson,5,BEFORE_SNAP,2022-09-13 03:11:50.7,22.0,DEN,right,73.00,25.79,0.29,0.40,0.03,241.26,308.80,NaN
433118,2022091200,3980,35459.0,Kareem Jackson,6,BEFORE_SNAP,2022-09-13 03:11:50.8,22.0,DEN,right,72.99,25.80,0.19,0.63,0.02,238.82,318.93,NaN
433119,2022091200,3980,35459.0,Kareem Jackson,7,BEFORE_SNAP,2022-09-13 03:11:50.9,22.0,DEN,right,72.98,25.81,0.11,0.71,0.01,237.20,343.56,NaN
433120,2022091200,3980,35459.0,Kareem Jackson,8,BEFORE_SNAP,2022-09-13 03:11:51,22.0,DEN,right,72.98,25.82,0.07,0.71,0.01,236.37,33.51,NaN
433121,2022091200,3980,35459.0,Kareem Jackson,9,BEFORE_SNAP,2022-09-13 03:11:51.1,22.0,DEN,right,72.99,25.82,0.11,0.65,0.01,235.72,76.98,NaN
433122,2022091200,3980,35459.0,Kareem Jackson,10,BEFORE_SNAP,2022-09-13 03:11:51.2,22.0,DEN,right,73.01,25.81,0.17,0.58,0.02,236.46,98.90,NaN

Row count of tracking data for gameId = 2022091200:
7104700

         displayName  row_count  row_number
0      Abraham Lucas         61           1
1     Alex Singleton         61           2
2      Austin Blythe         61           3
3     Baron Browning         61           4
4      Bradley Chubb         61           5
5      Charles Cross         61           6
6    Colby Parkinson         61           7
7         D.J. Jones         61           8
8      DeeJay Dallas         61           9
9     Dre'Mont Jones         61          10
10      Gabe Jackson         61          11
11        Geno Smith         61          12
12    Jonas Griffith         61          13
13    Justin Simmons         61          14
14    Kareem Jackson         61          15
15  Marquise Goodwin         61          16
16      Mike Purcell         61          17
17   Patrick Surtain         61          18
18       Phil Haynes         61          19
19      Ronald Darby         61          20
20      Travis Homer         61          21
21       Will Dissly         61          22
22          football         61          23

In [34]:
# Display header info
print(f"Tracking data for football, gameId = {game_id}, playId = {play_id}:")
display(tracking_fb_filtered.head(10))

# Show total number of rows (frames)
print(f"\nTotal frame count: {tracking_fb_filtered.shape[0]}")

# Group by frameType and count
frame_type_counts = tracking_fb_filtered['frameType'].value_counts().reset_index()
frame_type_counts.columns = ['frameType', 'count']

print("\nFrame count by frameType:")
display(frame_type_counts)

Tracking data for football, gameId = 2022091200, playId = 3980:

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,gameId,playId,nflId,displayName,frameId,frameType,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
434455,2022091200,3980,NaN,football,1,BEFORE_SNAP,2022-09-13 03:11:50.3,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434456,2022091200,3980,NaN,football,2,BEFORE_SNAP,2022-09-13 03:11:50.4,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434457,2022091200,3980,NaN,football,3,BEFORE_SNAP,2022-09-13 03:11:50.5,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434458,2022091200,3980,NaN,football,4,BEFORE_SNAP,2022-09-13 03:11:50.6,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434459,2022091200,3980,NaN,football,5,BEFORE_SNAP,2022-09-13 03:11:50.7,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434460,2022091200,3980,NaN,football,6,BEFORE_SNAP,2022-09-13 03:11:50.8,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN
434461,2022091200,3980,NaN,football,7,BEFORE_SNAP,2022-09-13 03:11:50.9,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN
434462,2022091200,3980,NaN,football,8,BEFORE_SNAP,2022-09-13 03:11:51,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434463,2022091200,3980,NaN,football,9,BEFORE_SNAP,2022-09-13 03:11:51.1,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN
434464,2022091200,3980,NaN,football,10,BEFORE_SNAP,2022-09-13 03:11:51.2,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN

Total frame count: 61

Frame count by frameType:

     frameType  count
0  BEFORE_SNAP     49
1   AFTER_SNAP     11
2         SNAP      1

In [33]:

tracking_fb_filtered = tracking_filtered[tracking['displayName'] == 'football']

print(f"Tracking data for football, gameId = {game_id}, playID ={play_id}:")
display(tracking_fb_filtered.head(10))
print(tracking_fb_filtered.shape[0])

print("------------")
# Filter only football data for the specific game
tracking_fb = tracking[(tracking['displayName'] == 'football') & (tracking['gameId'] == game_id)]
tracking_fb_count = tracking_fb.groupby('playId').size().reset_index(name='frame_count')
tracking_fb_count = tracking_fb_count.sort_values(by='frame_count', ascending=False)
display(tracking_fb_count)

Tracking data for football, gameId = 2022091200, playID =3980:

/tmp/ipykernel_36/3132084519.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tracking_fb_filtered = tracking_filtered[tracking['displayName'] == 'football']
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,gameId,playId,nflId,displayName,frameId,frameType,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
434455,2022091200,3980,NaN,football,1,BEFORE_SNAP,2022-09-13 03:11:50.3,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434456,2022091200,3980,NaN,football,2,BEFORE_SNAP,2022-09-13 03:11:50.4,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434457,2022091200,3980,NaN,football,3,BEFORE_SNAP,2022-09-13 03:11:50.5,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434458,2022091200,3980,NaN,football,4,BEFORE_SNAP,2022-09-13 03:11:50.6,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434459,2022091200,3980,NaN,football,5,BEFORE_SNAP,2022-09-13 03:11:50.7,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434460,2022091200,3980,NaN,football,6,BEFORE_SNAP,2022-09-13 03:11:50.8,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN
434461,2022091200,3980,NaN,football,7,BEFORE_SNAP,2022-09-13 03:11:50.9,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN
434462,2022091200,3980,NaN,football,8,BEFORE_SNAP,2022-09-13 03:11:51,NaN,football,right,61.759998,23.940001,0.0,0.0,0.0,NaN,NaN,NaN
434463,2022091200,3980,NaN,football,9,BEFORE_SNAP,2022-09-13 03:11:51.1,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN
434464,2022091200,3980,NaN,football,10,BEFORE_SNAP,2022-09-13 03:11:51.2,NaN,football,right,61.759998,23.950001,0.0,0.0,0.0,NaN,NaN,NaN

61
------------

     playId  frame_count
106    3723          403
28      983          321
38     1344          272
8       315          259
90     3194          242
..      ...          ...
107    3747           88
65     2391           85
105    3685           85
111    4012           63
110    3980           61

[112 rows x 2 columns]

In [5]:
import pandas as pd

# Load the data
tracking = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/tracking_week_1.csv')
plays = pd.read_csv('/kaggle/input/nfl-big-data-bowl-2025/plays.csv')

# Preview the structure
print(tracking.columns)
print(plays.columns)

# Example: Find one play to study
sample_play = plays.sample(1, random_state=42)
gameId = sample_play['gameId'].values[0]
playId = sample_play['playId'].values[0]

print(f"Selected gameId: {gameId}, playId: {playId}")
print(sample_play[['playDescription', 'offenseFormation', 'personnelO']])

# Filter the tracking data for this play
play_tracking = tracking[(tracking['gameId'] == gameId) & (tracking['playId'] == playId)]

# Sort by frame to analyze frame-by-frame movement
play_tracking = play_tracking.sort_values(by=['frameId', 'nflId'])

# See player movement in first few frames
print(play_tracking.head())

# Optional: visualize players on field (basic)
import matplotlib.pyplot as plt

def plot_frame(df, frame_id):
    frame = df[df['frameId'] == frame_id]
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.set_xlim(0, 120)
    ax.set_ylim(0, 53.3)
    for _, row in frame.iterrows():
        ax.scatter(row['x'], row['y'], c='blue' if row['team'] == 'home' else 'red', label=row['team'])
        ax.text(row['x'], row['y'], row['jerseyNumber'], fontsize=8, ha='center')
    ax.set_title(f"Frame {frame_id}")
    plt.xlabel('X (yards)')
    plt.ylabel('Y (width)')
    plt.show()

# Plot the first frame of the play
plot_frame(play_tracking, frame_id=play_tracking['frameId'].min())

Index(['gameId', 'playId', 'nflId', 'displayName', 'frameId', 'frameType',
       'time', 'jerseyNumber', 'club', 'playDirection', 'x', 'y', 's', 'a',
       'dis', 'o', 'dir', 'event'],
      dtype='object')
Index(['gameId', 'playId', 'playDescription', 'quarter', 'down', 'yardsToGo',
       'possessionTeam', 'defensiveTeam', 'yardlineSide', 'yardlineNumber',
       'gameClock', 'preSnapHomeScore', 'preSnapVisitorScore',
       'playNullifiedByPenalty', 'absoluteYardlineNumber',
       'preSnapHomeTeamWinProbability', 'preSnapVisitorTeamWinProbability',
       'expectedPoints', 'offenseFormation', 'receiverAlignment',
       'playClockAtSnap', 'passResult', 'passLength', 'targetX', 'targetY',
       'playAction', 'dropbackType', 'dropbackDistance', 'passLocationType',
       'timeToThrow', 'timeInTackleBox', 'timeToSack', 'passTippedAtLine',
       'unblockedPressure', 'qbSpike', 'qbKneel', 'qbSneak',
       'rushLocationType', 'penaltyYards', 'prePenaltyYardsGained',
       'yardsGained', 'homeTeamWinProbabilityAdded',
       'visitorTeamWinProbilityAdded', 'expectedPointsAdded', 'isDropback',
       'pff_runConceptPrimary', 'pff_runConceptSecondary', 'pff_runPassOption',
       'pff_passCoverage', 'pff_manZone'],
      dtype='object')
Selected gameId: 2022102307, playId: 3582

KeyError: "['personnelO'] not in index"